"""create companies table

Revision ID: 33283f3ad3e7
Revises: 
Create Date: 2024-09-09 16:13:50.424240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33283f3ad3e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('legal_name', sa.String(length=128), nullable=False),
    sa.Column('trade_name', sa.String(length=128), nullable=False),
    sa.Column('cnae', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    # ### end Alembic commands ###
